apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: ochacafe
        image: cyberblack/ochacafe-tekton
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: LoadBalancer
  ports:
  - name: ochacafe
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: go