apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: app-test
        image: cyberblack/ochacafe-tekton:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  selector:
    app: test
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 30008